<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Version number -->
    <VersionPrefix>2.0.0</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)' == 'Debug'">dev</VersionSuffix>

    <FullVersion>$(VersionPrefix)</FullVersion>
    <FullVersion Condition="'$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</FullVersion>

    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <InformationalVersion>$(FullVersion)</InformationalVersion>

    <!-- Output Directory -->
    <ArtifactsPath>$(MSBuildThisFileDirectory)bin</ArtifactsPath>

    <!-- Code style warnings -->
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>