<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>exe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BsaLib/BsaLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Management.Automation" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
</Project>