<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="K4os.Compression.LZ4" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.Management.Automation" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
</Project>